name: Tyk Schema Validation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  schema-validation:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checking out Repo
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0
    - uses: actions/github-script@v6
      with:
        script: |
          const { execSync } = require('child_process')
          const { commits } = context.payload.pull_request
          const rawFiles = execSync(`git diff --name-only HEAD HEAD~${commits}`).toString()
          const files = rawFiles.split('\n').filter(Boolean)  
    - name: Listing Repo content
      run: |
        ls -la
        pwd
