name: Tyk Schema Validation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  schema-validation:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checking out Repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
    - name: Listing Repo content
      run: |
        ls -la
        pwd
    - name: 'Setup jq'
      uses: dcarbone/install-jq-action@v2
    - name: 'Check jq'
      # language=sh
      run: |
        which jq
        jq --version
